spring:
  application:
    name: feign-consumer
server:
  port: 40001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
eureka-client:
  ribbon:
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    ConnectTimeout: 1000
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true