spring:
  application:
    name: hystrix-consumer
server:
  port: 50000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
# 开启feign中的hystrix组件功能
feign:
  hystrix:
    enabled: true

# 全局配置
hystrix:
  command:
#    IService#retry(Integer):
#    wpCacheKey:
    default:
      circuitBreaker:
        # 熔断的前提条件(单位是个)：在一定时间窗口内，请求数量达到5个以后开始进行熔断判断
        requestVolumeThreshold: 5
        # 熔断的开启条件(单位是%)：在一定时间窗口内，如果请求数量达到以上阈值，且其中达到当前百分比数量的请求都是失败的，则开启熔断器
        errorThresholdPercentage: 50
        # 熔断器开启后，经过多久熔断器进入半开状态(单位是毫秒)。该配置正常要比时间窗口短，不然没啥作用。
        sleepWindowInMilliSeconds: 15000
      metrics:
        rollingStats:
          # 时间窗口(单位是毫秒)
          timeInMilliseconds: 20000
      execution:
        timeout:
          # 启用全局超时
          enable: true
        isolation:
          thread:
            # 超时时间(毫秒)
            timeoutInMilliseconds: 1000
            # 线程超时以后终止线程
            interruptOnTimeout: true
            # 线程取消的时候终止线程
            interruptOnFutureCancel: true
eureka-client:
  ribbon:
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    ConnectTimeout: 1000
    ReadTimeout: 8000
    OkToRetryOnAllOperations: true
# actuator暴露接口
management:
  endpoints:
    web:
      exposure:
        # 暴露所有的可监控的接口(endpoint)
        include: "*"
  endpoint:
    health:
      # 展示所有信息
      show-details: always
