spring:
  application:
    name: sleuth-traceA
  sleuth:
    sampler:
      # 所有数据均收集，如果只收集80%则赋值0.8即可
      probability: 1
  zipkin:
    base-url: http://localhost:62100
    sender:
      # 指定发送调用链路信息的方式为http
      type: web
# eureka服务中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
server:
  port: 62000
logging:
  file: ${spring.application.name}.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: sleuth-traceA
    description: test

