spring:
  application:
    name: eureka-client
server:
  port: 30000
eureka:
  client:
    service-url:
      #http://{Eureka-Server服务的IP地址/Eureka-Server服务的Port端口/eureka/}
      #必须有/eureka/这个后缀
      defaultZone: http://localhost:20000/eureka
