spring:
  application:
    name: eureka-client
server:
  port: 30000
eureka:
  instance:
    #在eureka-server的UI页面上，Status处显示当前服务的信息。默认显示的是{服务器ip:端口号}。如果自行设置的话，那么如果该服务多次启动，在
    #服务注册列表只能看到1个，因为id重复，所以看需要是否修改此配置
#    instance-id: wangpeng-instance-id:30000
    #每隔5秒钟，向续约中心发送一次续约指令
    lease-renewal-interval-in-seconds: 5
    #如果30秒内，eureka-server依然没有收到续约请求，判定本服务过期
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      #指明Eureka注册中心服务(即eureka-server服务)的地址，用于将该服务注册到注册中心，缺省值为 http://localhost:8761/eureka。
      #其实就是eureka-server提供了一个注册服务的接口(/eureka)，各个client服务通过此接口进行服务的注册、续费等操作
      #配置格式为：http://{Eureka-Server服务的IP地址/Eureka-Server服务的Port端口/Eureka-Server服务的servlet.context-path，没有则不需要/eureka/}。注意必须有/eureka/这个后缀
      #如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
      defaultZone: http://localhost:20000/eureka


