spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 根据eureka自动创建服务路由
          enabled: true
          # 生成的路由策略都转为小写
          lower-case-service-id: true
      # 集合类型属性，routes对象的属性有id、uri、predicates、filters等
      routes:
          # route路由策略唯一id
        - id: eurekaclient
          # 断言匹配成功后转发的地址。可以是注册中心的服务名称，也可以是ip:port或域名等形式，取决于locator中设置的创建路由的方式
          uri: lb://EUREKA-CLIENT
          # 设置断言：集合类型属性。
          # 如下设置断言类型为Path断言。如果请求路径能匹配/yml/**，则断言返回true，可以进行执行路由器的操作
          predicates:
            - Path=/yml/**
          # 设置过滤器：集合类型属性。
          # 如下设置即将请求中url端口号后或域名后的第一个地址符删除掉。比如请求地址http://localhost:65000/yml/test/sayHi，那么过滤器会将yml这个地址符删除
          filters:
            - StripPrefix=1
server:
  port: 65000

# eureka服务中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always