spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 根据eureka自动创建服务路由
          enabled: true
          # 生成的路由策略都转为小写
          lower-case-service-id: true
server:
  port: 65000

# eureka服务中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always